// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD87zPbT6ZBrYeSO4dMlzN4rWB5u722D2Q',
    appId: '1:993385667131:web:56d1c801dfd0becb7f5a1e',
    messagingSenderId: '993385667131',
    projectId: 'improv-c142d',
    authDomain: 'improv-c142d.firebaseapp.com',
    storageBucket: 'improv-c142d.appspot.com',
    measurementId: 'G-3HPCHDFGC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdU72aJEVXZAHou3Ef1EeSFX-Sd5yKSDU',
    appId: '1:993385667131:android:bf346ef5283cc6857f5a1e',
    messagingSenderId: '993385667131',
    projectId: 'improv-c142d',
    storageBucket: 'improv-c142d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZFDeKeM5Pg_beI9MLzBi9MLEv3NIMah0',
    appId: '1:993385667131:ios:8588fc688e9fb88c7f5a1e',
    messagingSenderId: '993385667131',
    projectId: 'improv-c142d',
    storageBucket: 'improv-c142d.appspot.com',
    iosBundleId: 'com.example.improw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZFDeKeM5Pg_beI9MLzBi9MLEv3NIMah0',
    appId: '1:993385667131:ios:8588fc688e9fb88c7f5a1e',
    messagingSenderId: '993385667131',
    projectId: 'improv-c142d',
    storageBucket: 'improv-c142d.appspot.com',
    iosBundleId: 'com.example.improw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD87zPbT6ZBrYeSO4dMlzN4rWB5u722D2Q',
    appId: '1:993385667131:web:2dad26b094b4dd997f5a1e',
    messagingSenderId: '993385667131',
    projectId: 'improv-c142d',
    authDomain: 'improv-c142d.firebaseapp.com',
    storageBucket: 'improv-c142d.appspot.com',
    measurementId: 'G-H97M2V1967',
  );
}
